services:
  opresent-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: smauii-opresent:latest
    container_name: smauii-opresent-app
    environment:
      TZ: Asia/Jakarta
    env_file:
      - .env
    networks:
      - nginx-net
    restart: always
    volumes:
      - .:/var/www/html
      - opresent_uploads:/var/www/html/writable/uploads
      - opresent_photos_masuk:/var/www/html/public/assets/img/foto_presensi/masuk
      - opresent_photos_keluar:/var/www/html/public/assets/img/foto_presensi/keluar
      - opresent_files:/var/www/html/public/assets/file/surat_keterangan_ketidakhadiran

volumes:
  opresent_uploads:
    external: true
  opresent_photos_masuk:
    external: true
  opresent_photos_keluar:
    external: true
  opresent_files:
    external: true

networks:
  nginx-net:
    external: true
